services: docker
env:
  global:
    - IMAGE_NAME: devzx/slow
    - secure: "KldyzUqCSrQHQRWWV5gN1O/lMCWU7ic8/Yp57LG18i7wKM3YCPa1s3Tce6C49z5h6u8WIQ4kuvUoH7bMFXbssQDqEQq2F4vv9RKv+IlMb4kCSTYnz2dFBNrJZFNk+oMVAYzOmDN8w89gcdibrg5FfneQEYhUC1/bvaUr8a+FTfDkS7jC30LtTlxnsadGABARKey/B7t/uNWAujOOdZZyeF7ojQeLnRL3Zx3Whyit6fSpUKDSMA+jDQD8et2OhdVXuteRpE1mCgbmYmcPKbuMOc8VYGjJzCeDZSTOfis518gOLxMKod23s52/KO+5x7I/XRYYT69RSXw0vW+bG0AT5fcWY4XslCmy9+oi6yVYT3SD6g+ngFxnaQ9FoRRQ4xPcr6zek5yoOwA1o7fS1LemCfro0QdFKU6pJmZ6Bkpk5dQcNZXsKesENMh3smPjtoSO+HfTfobt9WiSrRM67ZmjKecr07oYwjqv5FXbqJOH2J4NuQRrMXrjNoVDxyhf8fZBWm1xyXO310EjSzPTzCECopNGX8sl5G0wMWgOHwO7DqFmJwDGkkG0EWHtdkR818f3FA+65wiJrKuf/Nsd72u5HKd0/r4Br3tNAgHcT+dB2U8JGqhps6awWpS5G16ld1AqyL5aOCID7+pvUq71zcO6deUopkGM1R2MYP3qRfQJcdw="
    - secure: "dJBsD2KyY88iuEIVSo/0cnksvaE81hrg8FZdxeZxTinYfihO1TpfmFJ5vbokhjjYITWhErQtvl8CUDTlJOJrIlG1M2LLNSvX3D2Gn10vwOHybycErR9ej1aug48u/FQvkIu2GYWHsbhEm8nDrf3j01cSE/SJt7HhjfqS7NHA7qRilt0coiKGeWIbR2MdbrtwlRT7LKMBOB85QMjLlpVFsF8WsVEodfdOChKsb1vwaHhSRANA5PS+B07BGxoDARS9OeUOF1q4hiDlpYqpgeaDE/W3nuC2Rq8MgnvfYHC8HbJwBrfgwjNRuRNl8kZCoe/sTeafgVqp6ZsDiDzYrtJbcd9tdHbO+eIST3TM9i2LQJvId19OnQst+pAPg+hxy3oMGdVSr0xJJDiacR27sxPVY3rHJVzTcmzRu58XYlnk2SkvoRSDkx9UR/sugxP11rXLXfKORyV3c4zzAGtHcCFlt7Zop8FiHzuMWqtJREF5r+eG1aygQTbhqBV2RGonxdJ4R+P70p4dB/xshzQTQ7Xw/E0F5upprQ+L2pXP4KLWzdGBmj7dEM0Iero77SJD5PANEFReIJPDAye7sg7SjHYzIaa0qBvAonA+1cy0h5fAlgI8TbTaO4jFU+KqTyPZXqB8wiwi73Dt3sdoz6ArCCtlvYcdvd0i5GHaHQV1bBUbWb4="

install: true

notifications:
  email: false
  slack:
    secure: "to3+NZQzhn5hTDQ+27fl2t3q7bQXb+i9/zF117sU5dpM/xKjyCPBz4L39tD0znLu4CGYvqe117Nb5WoOtsL/Xgaaa/WnhvbHXRPqh70PzZc1FqnOuEuDEMlFlmhwnK5IA1KdnEyUGtUWAX1MxQxV4r7Qco76KjYPgFXcYT4f6K6A5OtJHnqPLv6uyd3pAlua7mf1wSdwWizQ3LIGYlobbcuIn/wLAlwfpKqEiZS8O8/EW+r7TOnfpcbiBBxm8ah2CJgcuQMfo2q1SJ9GJsrmhO1hPHlIU+nosrZG2JscDkGo9oLqJZRC0KeKu3l4TL4VjnjXGFRqOIFPsXZzCPkLL9OS91tn5shEnt2Q03HAY0T5oiKoFuBow/dGN6HkD60kOQZSd7ZiNpql9kNOM7QJ02BkE+/BrakGtJ4UGwB57aVTqC81Kt7H3NRVmbkSqa6KcvmvQQKj41tn0EF2FMCPMS5lQdZCPenONOWTcwo4ff5vZs+y2aIFAL+lpq9ra7mrKM0+lO/jAkN3dlEryLrJ3LldB5/KIk57wKxBy9y49BrfAdxZ33pGZ37dlMJdA4pbQgMf3M6fM2KTfBkCtZ26kKuN855CDOKOmAgzInONteHEbb6DUlnvW0nb4a4wn2KOJD1Jkm8XJvjgmUc/vbs14/nETEo3IEldRfSbcl4N78U="

script:
  - docker build -t $IMAGE_NAME .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_COMMIT

deploy:
  provider: script
  script: docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$TRAVIS_COMMIT
  on:
    branch: master
