services: docker
env:
  global:
    - IMAGE_NAME: devzx/slow
    - secure: "r6MvqLOFcXAXzGv854h1uREcEWY8eov4d0n+ZORSMZJV/XQ7jfcMqC0jGbNXr71ZEfTLE6eJYl3KaLArQgMkQSSFPTe3PiYrPGJoWIfdYRw4pAP9D8WutwfFKYlubRs6YlYzeYZ46wchlSdFQ4cTGECN4dQJiMeApCpeXH9vbglrnDprFF3G0A+Ffzlej1v4/wh8d2zun+4PRa+vEkZfF2qxK+ZMcB+QgGZOW/eutAxK/qQ+AVWCfDi1vNQCtGlLfgrnW7eetAJtz6er3BPLT9sNoF4Ent+dtP6Dso63GJj4xKC+7fhOB5ZwvTmZOMTrP4fWOAoLHsr+a4ULwwDWWsmD63MvbQyhXE79Yd6rYV5fdmGRUGVLwO4bH2dqBdLpy5oA/rUbXSj6CNnEjNmXbVLyh0jJ9I3Q3z2fMx4g2v40YzNhf3o2n4t8cDFXrqakbCfHCBa1qUMhlYrZKbndOxOPnt3DIf1UoB0yAq4V5Mk6oJH/CDWOERG6ifWTPDfFSr1ZBAqypcQrbp87HhLsyxEIuGmXS9h0CGzDLwp/iGFWbrXZehswiOsETon6fMMHXPQPyYOi6sBAgazTaFWb3FGIwGjX3r2K4g7Y7OtVkl0pEn9v3hAtsuMI6THjwtKyKsPfKzLjRf8aPPrO+sfKWrGjyQNt1kNR42uQwf4IHjg="
    - secure: "dJBsD2KyY88iuEIVSo/0cnksvaE81hrg8FZdxeZxTinYfihO1TpfmFJ5vbokhjjYITWhErQtvl8CUDTlJOJrIlG1M2LLNSvX3D2Gn10vwOHybycErR9ej1aug48u/FQvkIu2GYWHsbhEm8nDrf3j01cSE/SJt7HhjfqS7NHA7qRilt0coiKGeWIbR2MdbrtwlRT7LKMBOB85QMjLlpVFsF8WsVEodfdOChKsb1vwaHhSRANA5PS+B07BGxoDARS9OeUOF1q4hiDlpYqpgeaDE/W3nuC2Rq8MgnvfYHC8HbJwBrfgwjNRuRNl8kZCoe/sTeafgVqp6ZsDiDzYrtJbcd9tdHbO+eIST3TM9i2LQJvId19OnQst+pAPg+hxy3oMGdVSr0xJJDiacR27sxPVY3rHJVzTcmzRu58XYlnk2SkvoRSDkx9UR/sugxP11rXLXfKORyV3c4zzAGtHcCFlt7Zop8FiHzuMWqtJREF5r+eG1aygQTbhqBV2RGonxdJ4R+P70p4dB/xshzQTQ7Xw/E0F5upprQ+L2pXP4KLWzdGBmj7dEM0Iero77SJD5PANEFReIJPDAye7sg7SjHYzIaa0qBvAonA+1cy0h5fAlgI8TbTaO4jFU+KqTyPZXqB8wiwi73Dt3sdoz6ArCCtlvYcdvd0i5GHaHQV1bBUbWb4="

install: true

notifications:
  email: false
  slack:
    secure: FMo9rryIloNsFRmUyLAcIyIOrsdLHvDxJ8tjDJeJfl3AVkimGlQxxt1PyhZxCG/pR6zPFXrSHf70gsWNLtVwtWSLCRNAZ0ui0HtQB//OtnadIyi8FaNGcUI9Jd9iz9jhb+BgUD4GoMjuJb8p+A9Z+59ecLMMybrqdkTSAAoYF+Fe8ZZ+3G8IGommYEQPIil6ZXVyXPE5IRUiCByVTHZgpWOSmAFnURwyIUCKGRtSBWt3ZdYplKDEyyKTEySOTacNZd4rXWjEjd5e0sL9Wptl4aXepPrA/niWAULYfjUDIH8WZS/l7um9g2cJIT8YTQGeBJIaLsdqIURTjs2MPEmVmEyb7Rt6wWXG1I/DuKVMz90WLcfUG3cRRXXZifn2FnxXHWJEL0mWibcDBVTpLxxckwCqyNqu/5FruH0Z01D4GUcHqdmNzh4LNRBqeuf5MjoSqtoUX7g+bOQ7O/IwMJnXdHtZyI0yyJPwKxPmnek0FFXZ3zF1CEttWfPfXYWHw3e6xu3Ln2PlheIjoq1r2sfVt0x74Nq8+FCvk5wqaI6V+/tzZmuctMBMVN4RAlrb+KTLO3dsSWCi5iLAVjIZbhRS1tipF1bh3NB7h4BqZgr3OEX8zd/kyd8a/atXNMZLrtIo/00WVxEd3wCwyNNkHUPr92haYgHrhnrKb+tkda8v138=

script:
  - docker build -t $IMAGE_NAME .

before_deploy:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_COMMIT

deploy:
  provider: script
  script: docker push $IMAGE_NAME:latest && docker push $IMAGE_NAME:$TRAVIS_COMMIT
  on:
    branch: master
